service: recoordBackend
# app and org for use with dashboard.serverless.com
app: recoord
org: lpolito

provider:
  name: aws
  # runtime which individual functions will override
  runtime: python3.8
  # service wide environment variables
  environment:
    GRAPHQL_ENDPOINT: ${opt:graphqlEndpoint}

package:
  individually: true

functions:
  fingerprint:
    runtime: python3.8
    module: src/fingerprint
    handler: handler.fingerprint_handler
    timeout: 60
    events:
      - http:
          path: /fingerprint
          method: post
    layers:
      - arn:aws:lambda:us-east-1:965185891634:layer:ffmpeg:1
    package:
      include:
        - src/fingerprint/**
      exclude:
        - "**"
        - __pycache__

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    invalidateCaches: true
    useStaticCache: false
    dockerizePip: non-linux
    slim: true
    slimPatterns:
      - "**/tests/**"
      - "**/doc/**"
