# Generated by Django 3.0.2 on 2020-01-20 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('youtube', 'YouTube')], default='youtube', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=7)),
                ('origin_id', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='coord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coord',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coord',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coord',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, editable=False, max_length=20)),
                ('time_offset', models.DecimalField(decimal_places=2, editable=False, max_digits=7)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coords.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('time_position', models.DecimalField(decimal_places=2, max_digits=7)),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coords.Coord')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coords.Video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
