# Generated by Django 3.0.2 on 2020-01-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coords', '0002_auto_20200120_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='hash',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='time_offset',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
